---
- hosts:               all
  become:              yes
  become_method:       sudo

  environment:
    NODE_ENV:          development

  vars_files:
    - vars/public.yml
    - vars/secret.yml

  pre_tasks:
    - name:            Install PostgreSQL, Nodejs, tmux dependancies
      apt:             name="{{ item }}"
      with_items:      "{{ packages }}"

  tasks:
    - name:            Create mangal group
      group:           name=mangal state=present
    - name:            Create mangal user
      user:            name=mangal comment="Mangal user" group=mangal home=/var/mangal
    - name:            Create postgres user
      user:            name=postgres comment="Postgres user"
    - name:            Create mangal_bot user
      become:          true
      become_user:     postgres
      postgresql_user:
        name:          mangal_bot
        password:      "{{ db_pass }}"
    - name:            Create mangal databases
      become:          true
      become_user:     postgres
      postgresql_db:   name="{{ item }}"
      with_items:      "{{ dbs }}"
    - name:            Add Postgis extensions
      become:          true
      become_user:     postgres
      postgresql_ext:  name=postgis db="{{ item }}"
      with_items:      "{{ dbs }}"
    - name:            setup .pgpass
      become:          true
      become_user:     mangal
      template:
        src:           templates/.pgpass.j2
        dest:          ~/.pgpass
        mode:          0600
    - name:            Install pm2
      npm:
        name:          pm2
        global:        yes
    - name:            Install nginx
      apt:             name=nginx state=present update_cache=yes
      notify:
        - start nginx
    - name:            configure nginx
      copy:            src="{{ item }}" dest=/etc/nginx/sites-available/
      with_fileglob:
        - nginx/*
      notify:
        - restart nginx

  environment:
      ORCID_CLIENTID:     "{{ ORCID_CLIENTID }}"
      ORCID_CLIENTSECRET: "{{ ORCID_CLIENTSECRET }}"
      ORCID_CALLBACK:     "{{ ORCID_CALLBACK }}"
      PORT_MANGAL_OAUTH:  "{{ PORT_MANGAL_OAUTH }}"

  handlers:
    - name:            restart postgresql
      service:         name=postgresql state=restarted
    - name:            restart nginx
      service:         name=nginx state=restarted
    - name:            start nginx
      service:         name=nginx state=started
