---
- hosts:               poisotlab
  become:              yes
  become_method:       sudo

  vars_files:
    - vars/public.yml
    - vars/secret.yml

  pre_tasks:
    - name: Add NodeJS latest version repository
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - name:            Install PostgreSQL, Nodejs, tmux dependancies
      apt:             name="{{ item }}"
      with_items:      "{{ packages }}"
    - name: set environmental variables
      lineinfile:
        dest: /etc/environment
        line: "{{ item }}"
      with_items:
        - "ORCID_CLIENTID={{ ORCID_CLIENTID }}"
        - "ORCID_CLIENTSECRET={{ ORCID_CLIENTSECRET }}"
        - "ORCID_CALLBACK={{ ORCID_CALLBACK }}"
        - "PORT_MANGAL_OAUTH={{ PORT_MANGAL_OAUTH }}"

  tasks:
    - name:            Create mangal group
      group:           name=mangal state=present
    - name:            Create mangal user
      user:            name=mangal comment="Mangal user" group=mangal home=/var/mangal password={{ mangal_pass }}
    - name:            Create postgres user
      user:            name=postgres comment="Postgres user"
    - name:            Create mangal user
      become:          true
      become_user:     postgres
      postgresql_user:
        name:          mangal
        password:      "{{ db_pass }}"
    - name:            Create mangal databases
      become:          true
      become_user:     postgres
      postgresql_db:   name="{{ item }}"
      with_items:      "{{ dbs }}"
    - name:            Add Postgis extensions
      become:          true
      become_user:     postgres
      postgresql_ext:  name=postgis db="{{ item }}"
      with_items:      "{{ dbs }}"
    - name:            setup .pgpass
      become:          true
      become_user:     mangal
      template:
        src:           templates/.pgpass.j2
        dest:          ~/.pgpass
        mode:          0600
    - name:            Install pm2
      npm:
        name:          pm2
        global:        yes
    - name:            Install nginx
      apt:             name=nginx state=present update_cache=yes
      notify:
        - start nginx
    - name:            configure nginx
      copy:            src="{{ item }}" dest=/etc/nginx/sites-available/
      with_fileglob:
        - nginx/*
      notify:
        - restart nginx

  handlers:
    - name:            restart postgresql
      service:         name=postgresql state=restarted
    - name:            restart nginx
      service:         name=nginx state=restarted
    - name:            start nginx
      service:         name=nginx state=started
